#!/usr/bin/ruby

require 'nwn/all'


Dir.foreach('./') do |e|
	if(Dir.exist?(e) and !(e[0,1] == '.'))
		erf = NWN::Erf::Erf.new
		erf.year = $year if $year
		erf.day_of_year = $day_of_year if $day_of_year
		Dir.foreach(e) do |f|
			if(!File.directory?(f))
				erf.add_file File.basename(f), File.open(e+'/'+f, "r")
			end
		end
        file = File.new(e+'.hak', "wb") 
		erf.write_to(file)
		file.close
	end
end